version: "3.8"

services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1880
      MYSQL_USER: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  # Frontend services
  frontend1:
    container_name: kartingrm-frontend-1
    image: duvanvergara/kartingrm-frontend:latest
    ports:
      - 3001:80
    networks:
      - frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  frontend2:
    container_name: kartingrm-frontend-2
    image: duvanvergara/kartingrm-frontend:latest
    ports:
      - 3002:80
    networks:
      - frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  frontend3:
    container_name: kartingrm-frontend-3
    image: duvanvergara/kartingrm-frontend:latest
    ports:
      - 3003:80
    networks:
      - frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  # Backend services
  backend1:
    container_name: kartingrm-backend-1
    image: duvanvergara/kartingrm-backend:latest
    ports:
      - 8091:8090
    environment:
       DB_HOST: db
       DB_PORT: 3306
       DB_USERNAME: root
       DB_PASSWORD: 1880
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network

  backend2:
    container_name: kartingrm-backend-2
    image: duvanvergara/kartingrm-backend:latest
    ports:
      - 8092:8090
    environment:
       DB_HOST: db
       DB_PORT: 3306
       DB_USERNAME: root
       DB_PASSWORD: 1880
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network

  backend3:
    container_name: kartingrm-backend-3
    image: duvanvergara/kartingrm-backend:latest
    ports:
      - 8093:8090
    environment:
       DB_HOST: db
       DB_PORT: 3306
       DB_USERNAME: root
       DB_PASSWORD: 1880
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    container_name: kartingrm-nginx-frontend
    restart: always
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    container_name: kartingrm-nginx-backend
    image: nginx:latest
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  mysql_data: